### ISSUE TITLE
Non zend-related library getting renamed in composer.json

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-migration#20]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary

When I upgrade one of our projects, the laminas-migration `migrate` command renames a package inside of the `composer.json` because its name contains `zend-config`.

#### Current behavior

The laminas-migration `migrate` command renames a package inside of the `composer.json` because its name contains `zend-config`.
Other dependencies, also containing the `zend-` prefix, stay untouched.

#### How to reproduce

```bash
$ mkdir foo
$ cd foo
$ composer init
$ <Enter your stuff>
# add manually a dependency called `vendor/zend-config` (you can just modify the `composer.json` directly without running `install` or `require`)
$ laminas-migration migrate
$ cat composer.json
```

#### Expected behavior

Package does not get renamed.

####  Before
```json
{
    "name": "max/foo",
    "require": {
        "bar/zend-config": "*",
        "bar/foo-zend-config": "*",
        "bar/zend-http": "*"
    }
}
```

#### After
```json
{
    "name": "max/foo",
    "require": {
        "bar/laminas-config": "*",
        "bar/foo-laminas-config": "*",
        "bar/zend-http": "*",
        "laminas/laminas-dependency-plugin": "^0.2"
    }
}
```

**Comment by boesing** [comment]
Well, this actually relates to the [laminas-zendframework-bridge/replacements#L437](https://github.com/laminas/laminas-zendframework-bridge/blob/master/config/replacements.php#L437)

**Comment by weierophinney** [comment]
This is a hard one for us to resolve, because we often need to replace some of these strings specifically (due to use as config keys).

We use `strtr` internally to do replacements, because we found `preg_replace` was several orders of magnitude slower for these tasks (something that now takes minutes took closer to an hour when using PCRE), and because it prevents issues such as overwriting strings that have already been rewritten (you'll see we have a number of replacements that replace with themselves; by doing this, we prevent later rules from rewriting those strings).

Now, that said: I don't see any rules in the replacements that would replace any of the specific strings you've noted above. We have rules for `zendframework/zend-config` and `zendframework/zend-http`, but none for the more generic versions you've listed, so those should not get rewritten. That said, I've verified the above, and will work on a solution soon.

**Comment by boesing** [comment]
We have packages which extend or relates to some of the `zend-*` packages. Thus, our namespace and the package name contains `Zend\Config`/`zend-config` or `Zend\Http`/`zend-http` to see what packages they relate to. But actually only the `zend-config` package is being renamed in the `composer.json`, the other files stay the same (so do their namespaces).

I think specific migrations would be better than a general strstr on the whole file. I guess that was the best way to providing a migration tool asap. But probably there will be a version in the future with specific replacements for specific parts of the code. 
I think, using php-parsers will make the migration take longer than it does actually due to more complicated migrations.
But this would provide migrations for docblocks, migrations for namespaces, migrations for `composer.json` files, and so on.

> Now, that said: I don't see any rules in the replacements that would replace any of the specific strings you've noted above. 

I've linked the file with the line which probably replaces the part of the `composer.json`.

**Comment by weierophinney** [comment]
> I've linked the file with the line which probably replaces the part of the `composer.json`.

And if that's there, it's because it's likely used within code as a config key or similar.

As such, going to leave this open, but we likely cannot fix it.

**Comment by boesing** [comment]
Same as. https://github.com/laminas/laminas-migration/issues/21#issuecomment-571793473
