### ISSUE TITLE
Replaces "api-skeletons/zf-oauth2-doctrine" & "api-skeletons/zf-oauth2-doctrine-identity" with non-existent packages

### ISSUE THREAD

**Issue by NickClaywell** [laminas/laminas-migration#41]
#### Summary

I ran the migration tool on a ZF2 Apigility project that is using `api-skeletons/api-tools-oauth2-doctrine` and `api-skeletons/api-tools-oauth2-doctrine-identity` and it replaces those packages in composer.json with `api-skeletons/api-tools-oauth2-doctrine` and `api-skeletons/api-tools-oauth2-doctrine-identity`, which do not exist.

#### Current behavior

After running the migration tool, running `composer install` results in:
![image](https://user-images.githubusercontent.com/2110512/77577420-c3fc3880-6ea4-11ea-82be-5f368475e4bb.png)

#### How to reproduce

Run the migration tool on an Apigility project that has the packages above.

#### Expected behavior

The tool replaces the zf-oauth2-doctrine and zf-oauth2-doctrine-identity packages with the migrated Laminas versions or does not replace them (or references to them) at all.

**Comment by NickClaywell** [comment]
Actually, I just found that those packages were updated/renamed for Laminas migration here: 

https://github.com/api-skeletons/oauth2-doctrine
https://github.com/API-Skeletons/oauth2-doctrine-identity

**Comment by michalbundyra** [comment]
@NickClaywell That is a tough one. in api-skeletons there are many packages with `zf-` prefix and because of that all these are replaces to `api-tools-`. We can add the rule to not replace:
`api-skeletons/zf-`, but then we would need to check all of these libraries and also add rules for configuration keys, like: https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/oauth2.doctrine-orm.global.php.dist#L9

As you noted these libraries were already migrated to new names and Laminas support, but there are much more packages where we will have the same problem.
