### ISSUE TITLE
Add big fat warning that "vendor" will be deleted in the process

### ISSUE THREAD

**Issue by glensc** [laminas/laminas-migration#45]
It's not okay that the migration tool removes "vendor" directory in the process. Users may have changes there that they want to preserve.

The tool should either:
1. not remove vendor directory
2. ask user confirmation that it's okay to proceed and the vendor dir be deleted in process.

**Comment by glensc** [comment]
I for example miss that some vendor package I had installed with prefer-source and added extra remotes and branches. this information is now lost.

**Comment by froschdesign** [comment]
The migration guide already contains these information: "[1. Preparation – Make sure your code is under version control](https://docs.laminas.dev/migration/#make-sure-your-code-is-under-version-control)"

**Comment by glensc** [comment]
@froschdesign perhaps you missed the point that I was talking about projects under "vendor" directory.

it's considered wrong to commit your vendor to the project repository.

**Comment by froschdesign** [comment]
@glensc 
> perhaps you missed the point that I was talking about projects under "vendor" directory.

And the migration guide contains:

> The migration tool changes source code, updates templates, modifies your composer.json and **removes your composer.lock and vendor/ subdirectory**, among other things

And yes, this important information should be better highlighted.

**Comment by glensc** [comment]
this issue is about RFE for requesting user to type "yes", or can confirm that they understand with risk with "--yes" (for example) command line argument.

**Comment by glensc** [comment]
perhaps to suggest to make fresh clone when migrating?

```
git clone /path/to/original/repo laminas-migration-project
cd laminas-migration-project
...
```

**Comment by weierophinney** [comment]
@glensc —

> it's considered wrong to commit your vendor to the project repository.

And it's precisely for this reason: because the contents are _managed and populated by tooling_. Generally, if you find yourself modifying the contents of `vendor` manually, it's a sign that you need to move the code out of that directory, so you _can_ manage it via VCS.

That said, I'm not at all against a big old warning as you start the process, and will work on that today. But when the answer to that question is "no", the tooling will need to abort, as `composer install` will fail on completion if the original dependencies are present (this is something we discovered when writing the tool, and it's the reason we blow away the `vendor/` directory).

**Comment by glensc** [comment]
Another idea that did come to the light, perhaps rename the directory, not delete. `mv vendor vendor.laminas-migrate-backup-$(date +%Y%m%d)`

I assume the reason for removal is that it confuses composer install command, i.e it's too complicated to replace packages appropriately and reliably, so the vendor dir is just removed. but the same problem could be done without delete using rename command.

**Comment by glensc** [comment]
the outcome:

![image](https://user-images.githubusercontent.com/199095/85875963-b32dcc80-b7dd-11ea-9ea9-6c307bcdb786.png)
